CREATE TABLE BENEFICIO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    VALOR DECIMAL(15,2) NOT NULL,
    ATIVO BIT DEFAULT 1,
    VERSION BIGINT DEFAULT 0
);
